# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 277e36b11bd85ca75193ed5232831efefa6bac9c4e6824fe415aae300cc2ad061eacba5f84d8e541eaa3a0746cf0f8e46190889bdaba645ccc9a4c92726704cd

test:
  secret_key_base: 7662a65d09a880da70d8dac4e4b035edd0ea9218afcb4bb2654e39447a205af8dc3ab68c0a45be5e75d03fe9a92fef0dd50d5ee47c2a96ff34370e3e8c708ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
